baseURL = "https://lmouline.github.io/uscript/"
languageCode = "en-us"
title = "UScript"
theme = "hugo-theme-techdoc"
canonifyURLs = true

metaDataFormat = "yaml"

[Params]
    description = "Scripting language that handles uncertain data"
    github_repository = "https://github.com/lmouline/uscript"
    version = "1.0.0-SNAPSHOT"

    github_doc_repository = "https://github.com/lmouline/uscript"
    github_doc_folder = "website"

    css = ["css/warning_bootstrap.css", "css/code-style.css"]


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1